name: reviewdog
on: [pull_request]

jobs:
  php_codesniffer:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: hrysd/action-php_codesniffer@v1
        with:
          github_token: ${{ secrets.github_token }}
          standard: phpcs.xml
          target_directory: .
