name: reviewdog
on: [pull_request]
jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: phpcs
        uses: MiddleFieldInc/PHPAnalyseDog@v0.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          phpcs_args: '. --standard=phpcs-custom.xml'

