name: Code style (PSR12)
on: [pull_request]
jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: "7.4"
          tools: phpcs
      - name: Fetch base branch
        id: base_branch
        run: |
          git fetch --progress origin ${{ github.base_ref }}
          files=$(git diff --diff-filter=ACM --name-only origin/${{ github.base_ref }} | xargs)
          echo $files
          echo '::set-output name=TEST::files'
      - name: Setup reviewdog
        run: |
          echo $files
          echo ${{ steps.base_branch.output.TEST }}
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/
      - name: Run PHP Code Sniffer on added and modified files
        run: 
          phpcs --report=json --standard=phpcs.xml `git diff --diff-filter=ACM --name-only origin/${{ github.base_ref }} | xargs` 
          | jq -r ' .files | to_entries[] | .key as $path | .value.messages[] as $msg | "\($path):\($msg.line):\($msg.column):`\($msg.source)`<br>\($msg.message)" '
          | reviewdog -tee -efm="%f:%l:%c:%m" -reporter=github-pr-review -filter-mode="added" -fail-on-error=false -level="warning"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
