name: Code style (PSR12)
on: [pull_request]
jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP Action
        # You may pin to the exact commit or the version.
        # uses: shivammathur/setup-php@c596331f84de248c01c26db5a184880781e96e36
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: "7.4"
          tools: phpcs
      - name: Setup reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/
      - name: Run PHP Code Sniffer
        run: export PHPCS_FORMATTED=phpcs --report=json --standard=phpcs.xml . |
          jq -r ' .files | to_entries[] | .key as $path | .value.messages[] as $msg | "\($path):\($msg.line):\($msg.column):`\($msg.source)`<br>\($msg.message)" '

      - name: Publish warnings
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${PHPCS_FORMATTED} | reviewdog -efm="%f:%l:%c:%m" -name="${INPUT_TOOL_NAME}" -reporter=github-pr-review -filter-mode="added" -fail-on-error="true" -level="warning"
